name: Bank
main: me.dablakbandit.bank.BankPlugin
author: Dablakbandit
version: @version@
softdepend: [Core, Vault, Bankcraft, ChestBank, MysqlEconomyBank, Citizens, Skript, MVdWPlaceholderAPI, PlaceholderAPI, HeadDatabase, TimeIsMoney]
api-version: 1.13